### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai-192-marchenko#3]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
1) Відомо, що безпечна клієнт-серверна взаємодія може забезпечуватися через наступні ключи: 
відкритий ключ клієнта, закритий ключ клієнта, відкритий ключ сервера, закритий ключ сервера. 
Вкажіть, будь ласка, який ключ вами було використано під час налаштування безпечного оновлення 
GitHub-репозиторію змінами з локального Git-репозиторію.

**Comment by terranora** [comment]
Для налаштування безпечного оновлення GitHub-репозиторію змінами з локального Git-репозиторію, був використано мій клієнтський публічний ключ  - lab_key.pub, що має наступний вигляд

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC4N29uFp0nrD5T2U0nRNthJLP7EqLyLQOhrOCqH9PlXQAgMB5O/Dg2MgEQuv13lALW/mXMxsPEeD+xRiwe7xn6frZtLf8TsTo3Basrpuv8/OXDtKIQx646a7vu4XEHR29oYqz9p+J0KnW4QIYb8zO+2/AVDR12S6GrdQ0+QPPMsb6aBfjPHnx5lEb+bWUex92vxv7EBDPCJLUFy8Z96JeQD/XrlgqYe8Sji6IQp6QB+VKWqYcyvLyddR8zOkKINJBSYGmHEIpyjtG9iCU8MlSegnbNTr1n7DsaF+NEC0SQ1wmH7msMo2WlWhXIognG/u19hMZjA7pAzwpRA+awsP55YKp6kY2YFMD8l8vwIicWeiy3FY25ctdlnzVx55Fm+teztC1vbWctpkB4jpCELKLR+mrANc8FEpoRrdGPXTeRr8weQkvm9QGP1vX0eucLipXpCeY/RzjQ+Xh2AYvyrLLG43mpwcQeySY55BsNLjYO9Dmhxe1/+soQwiQpAz91fvk= lab0

**Comment by terranora** [comment]
Для налаштування безпечного оновлення GitHub-репозиторію змінами з локального Git-репозиторію, був використано мій клієнтський публічний ключ  - lab_key.pub, що має наступний вигляд

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC4N29uFp0nrD5T2U0nRNthJLP7EqLyLQOhrOCqH9PlXQAgMB5O/Dg2MgEQuv13lALW/mXMxsPEeD+xRiwe7xn6frZtLf8TsTo3Basrpuv8/OXDtKIQx646a7vu4XEHR29oYqz9p+J0KnW4QIYb8zO+2/AVDR12S6GrdQ0+QPPMsb6aBfjPHnx5lEb+bWUex92vxv7EBDPCJLUFy8Z96JeQD/XrlgqYe8Sji6IQp6QB+VKWqYcyvLyddR8zOkKINJBSYGmHEIpyjtG9iCU8MlSegnbNTr1n7DsaF+NEC0SQ1wmH7msMo2WlWhXIognG/u19hMZjA7pAzwpRA+awsP55YKp6kY2YFMD8l8vwIicWeiy3FY25ctdlnzVx55Fm+teztC1vbWctpkB4jpCELKLR+mrANc8FEpoRrdGPXTeRr8weQkvm9QGP1vX0eucLipXpCeY/RzjQ+Xh2AYvyrLLG43mpwcQeySY55BsNLjYO9Dmhxe1/+soQwiQpAz91fvk= lab0

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 2 бали
